export type AlertType =
  | 'GARAGE_WEBSOCKET_CONNECTION_FAILED'
  | 'GARAGE_OPEN_FAILED'
  | 'GARAGE_CLOSE_FAILED'
  | 'TV_ON_FAILED'
  | 'TV_OFF_FAILED'
  | 'TV_WEBSOCKET_CONNECTION_FAILED'
  | 'GET_WEATHER_FAILED';
